# Generated by Django 5.0.1 on 2024-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredient Description'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
