# Generated by Django 5.0.1 on 2024-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
